version: '3'
services:
  # redis:
  #   image: redis
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      # - redis
    environment:
      #  REDIS_URL: redis://redis:6379/12
       EDITOR: vi #for credentials editing
      #  WEBPACKER_DEV_SERVER_HOST: webpacker
       HITTAMAKLARE_DATABASE_HOST: db
       HITTAMAKLARE_DATABASE_PASSWORD: mysecretpassword
volumes:
  postgres-data:
  # redis data doesn't need to persist right now
